### ISSUE TITLE
ERROR SCSS

### ISSUE THREAD

**Issue by CharafouddineAhmed** [creativetimofficial/material-dashboard-angular2#55]
`ahmed@ahmed-Charafouddine:~/Bureau/projets/TIM$ ng serve 
Your global Angular CLI version (7.2.0) is greater than your local
version (6.0.3). The local Angular CLI version is used.

To disable this warning use "ng config -g cli.warnings.versionMismatch false".
** Angular Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200/ **
                                                                                                                      
Date: 2019-01-21T20:14:11.444Z
Hash: ee5ab95933cc5961e2b9
Time: 19261ms
chunk {layouts-admin-layout-admin-layout-module} layouts-admin-layout-admin-layout-module.js, layouts-admin-layout-admin-layout-module.js.map (layouts-admin-layout-admin-layout-module) 3.01 MB  [rendered]
chunk {main} main.js, main.js.map (main) 50.1 kB [initial] [rendered]
chunk {polyfills} polyfills.js, polyfills.js.map (polyfills) 468 kB [initial] [rendered]
chunk {runtime} runtime.js, runtime.js.map (runtime) 8.05 kB [entry] [rendered]
chunk {scripts} scripts.js, scripts.js.map (scripts) 800 kB  [rendered]
chunk {styles} styles.js, styles.js.map (styles) 24.4 kB [initial] [rendered]
chunk {vendor} vendor.js, vendor.js.map (vendor) 4.65 MB [initial] [rendered]

ERROR in ./src/assets/scss/material-dashboard.scss (./node_modules/raw-loader!./node_modules/postcss-loader/lib??embedded!./node_modules/sass-loader/lib/loader.js??ref--14-3!./src/assets/scss/material-dashboard.scss)
Module build failed: Error: ENOENT: no such file or directory, scandir '/home/ahmed/Bureau/projets/TIM/node_modules/node-sass/vendor'
    at Object.readdirSync (fs.js:764:3)
    at Object.getInstalledBinaries (/home/ahmed/Bureau/projets/TIM/node_modules/node-sass/lib/extensions.js:130:13)
    at foundBinariesList (/home/ahmed/Bureau/projets/TIM/node_modules/node-sass/lib/errors.js:20:15)
    at foundBinaries (/home/ahmed/Bureau/projets/TIM/node_modules/node-sass/lib/errors.js:15:5)
    at Object.module.exports.missingBinary (/home/ahmed/Bureau/projets/TIM/node_modules/node-sass/lib/errors.js:45:5)
    at module.exports (/home/ahmed/Bureau/projets/TIM/node_modules/node-sass/lib/binding.js:15:30)
    at Object.<anonymous> (/home/ahmed/Bureau/projets/TIM/node_modules/node-sass/lib/index.js:14:35)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.sassLoader (/home/ahmed/Bureau/projets/TIM/node_modules/sass-loader/lib/loader.js:46:72)
ℹ ｢wdm｣: Failed to compile.
`

**Comment by chelaruc** [comment]
@CharafouddineAhmed can you tell me what you have in `angular.json` file?
