### ISSUE TITLE
Free demo not working

### ISSUE THREAD

**Issue by technicallyrice** [creativetimofficial/material-dashboard-angular2#96]
### Version
2.4.0
### Reproduction link
https://jsfiddle.net/
### Operating System
macOS
### Device
Macbook Pro
### Browser & Version
Chrome 
### Steps to reproduce
1. Download the free demo
2. Run npm install
3. Run ng serve
### What is expected?
The application works
### What is actually happening?
First, npm install throws a whole lot of warnings and vulnerabilities. This is probably due to the insanely old node and npm versions in the package.json. Ignoring those, when you then run ng serve receive the following:

ERROR in TypeError: tooling_1.constructorParametersDownlevelTransform is not a function
    at downlevelFactory (/Users/andrewrice/dev/project/node_modules/@ngtools/webpack/src/angular_compiler_plugin.js:779:43)
    at /Users/andrewrice/dev/project/node_modules/typescript/lib/typescript.js:89229:37
    at /Users/andrewrice/dev/project/node_modules/typescript/lib/typescript.js:89313:78
    at Array.map (<anonymous>)
    at Object.transformNodes (/Users/andrewrice/dev/project/node_modules/typescript/lib/typescript.js:89313:52)
    at emitJsFileOrBundle (/Users/andrewrice/dev/project/node_modules/typescript/lib/typescript.js:89858:32)
    at emitSourceFileOrBundle (/Users/andrewrice/dev/project/node_modules/typescript/lib/typescript.js:89811:13)
    at forEachEmittedFile (/Users/andrewrice/dev/project/node_modules/typescript/lib/typescript.js:89563:34)
    at Object.emitFiles (/Users/andrewrice/dev/project/node_modules/typescript/lib/typescript.js:89792:9)
    at emitWorker (/Users/andrewrice/dev/project/node_modules/typescript/lib/typescript.js:95809:33)
    at /Users/andrewrice/dev/project/node_modules/typescript/lib/typescript.js:95770:66
    at runWithCancellationToken (/Users/andrewrice/dev/project/node_modules/typescript/lib/typescript.js:95861:24)
    at Object.emit (/Users/andrewrice/dev/project/node_modules/typescript/lib/typescript.js:95770:20)
    at AngularCompilerPlugin._emit (/Users/andrewrice/dev/project/node_modules/@ngtools/webpack/src/angular_compiler_plugin.js:1046:48)
    at AngularCompilerPlugin._update (/Users/andrewrice/dev/project/node_modules/@ngtools/webpack/src/angular_compiler_plugin.js:872:50)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)

---

**Comment by rarestoma** [comment]
Hi @technicallyrice,

Thank you for working with our products.

I tried now and it works on my side. Can you please tell me what versions of gulp and npm are you using? I have `npm v6.14.5` and `gulp v2.2.0`.

Thank you,
Rares

**Comment by niknoorakmal** [comment]
Same issue occur to me. Do we have to run gulp or what/.
